-- CREATE TABLE users (
--     id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
--     name VARCHAR(50) NOT NULL,
--     username VARCHAR(50),
--     password VARCHAR(20),
--     createdAt TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
